export const WISHLIST_LIST_REQUEST = 'WISHLIST_LIST_REQUEST'
export const WISHLIST_LIST_SUCCESS = 'WISHLIST_LIST_SUCCESS'
export const WISHLIST_LIST_FAIL = 'WISHLIST_LIST_FAIL'

export const WISHLIST_ADD_REQUEST = 'WISHLIST_ADD_REQUEST'
export const WISHLIST_ADD_SUCCESS = 'WISHLIST_ADD_SUCCESS'
export const WISHLIST_ADD_FAIL = 'WISHLIST_ADD_FAIL'
export const WISHLIST_ADD_RESET = 'WISHLIST_ADD_RESET'

export const WISHLIST_REMOVE_REQUEST = 'WISHLIST_REMOVE_REQUEST'
export const WISHLIST_REMOVE_SUCCESS = 'WISHLIST_REMOVE_SUCCESS'
export const WISHLIST_REMOVE_FAIL = 'WISHLIST_REMOVE_FAIL'

export const WISHLIST_CHECK_REQUEST = 'WISHLIST_CHECK_REQUEST'
export const WISHLIST_CHECK_SUCCESS = 'WISHLIST_CHECK_SUCCESS'
export const WISHLIST_CHECK_FAIL = 'WISHLIST_CHECK_FAIL'
